
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Tag','com_pixext.tag','{"special":{"dbtable":"#__pixext_tags","key":"id","type":"Tag","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/tag.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.tag')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Tag', 
	`table` = '{"special":{"dbtable":"#__pixext_tags","key":"id","type":"Tag","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/tag.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.tag');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Type','com_pixext.type','{"special":{"dbtable":"#__pixext_types","key":"id","type":"Type","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/type.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.type')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Type', 
	`table` = '{"special":{"dbtable":"#__pixext_types","key":"id","type":"Type","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/type.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.type');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Extension','com_pixext.extension','{"special":{"dbtable":"#__pixext_extensions","key":"id","type":"Extension","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/extension.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_type_id","targetTable":"#__pixext_types","targetColumn":"pixext_type_id","displayColumn":"type"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.extension')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Extension', 
	`table` = '{"special":{"dbtable":"#__pixext_extensions","key":"id","type":"Extension","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/extension.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_type_id","targetTable":"#__pixext_types","targetColumn":"pixext_type_id","displayColumn":"type"}]}'
WHERE (`type_alias` = 'com_pixext.extension');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Version','com_pixext.version','{"special":{"dbtable":"#__pixext_versions","key":"id","type":"Version","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/version.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_extension_id","targetTable":"#__pixext_extensions","targetColumn":"pixext_extension_id","displayColumn":"name"},{"sourceColumn":"pixext_tag_id","targetTable":"#__pixext_tags","targetColumn":"pixext_tag_id","displayColumn":"tag"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.version')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Version', 
	`table` = '{"special":{"dbtable":"#__pixext_versions","key":"id","type":"Version","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/version.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_extension_id","targetTable":"#__pixext_extensions","targetColumn":"pixext_extension_id","displayColumn":"name"},{"sourceColumn":"pixext_tag_id","targetTable":"#__pixext_tags","targetColumn":"pixext_tag_id","displayColumn":"tag"}]}'
WHERE (`type_alias` = 'com_pixext.version');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Log Type','com_pixext.logtype','{"special":{"dbtable":"#__pixext_log_types","key":"id","type":"Logtype","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/logtype.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.logtype')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Log Type', 
	`table` = '{"special":{"dbtable":"#__pixext_log_types","key":"id","type":"Log Type","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/logtype.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.logtype');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Log Ip','com_pixext.ip','{"special":{"dbtable":"#__pixext_log_ips","key":"id","type":"Ip","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/ip.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.ip')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Log Ip', 
	`table` = '{"special":{"dbtable":"#__pixext_log_ips","key":"id","type":"Log Ip","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/ip.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.ip');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Log','com_pixext.log','{"special":{"dbtable":"#__pixext_logs","key":"id","type":"Log","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/log.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_log_type_id","targetTable":"#__pixext_log_types","targetColumn":"pixext_log_type_id","displayColumn":"type"},{"sourceColumn":"pixext_log_from_id","targetTable":"#__pixext_log_ips","targetColumn":"pixext_log_ip_id","displayColumn":"ip"},{"sourceColumn":"pixext_license_id","targetTable":"#__pixext_licenses","targetColumn":"pixext_license_id","displayColumn":"licence_key"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.log')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Log', 
	`table` = '{"special":{"dbtable":"#__pixext_logs","key":"id","type":"Log","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/log.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_log_type_id","targetTable":"#__pixext_log_types","targetColumn":"pixext_log_type_id","displayColumn":"type"},{"sourceColumn":"pixext_log_from_id","targetTable":"#__pixext_log_ips","targetColumn":"pixext_log_ip_id","displayColumn":"ip"},{"sourceColumn":"pixext_license_id","targetTable":"#__pixext_licenses","targetColumn":"pixext_license_id","displayColumn":"licence_key"}]}'
WHERE (`type_alias` = 'com_pixext.log');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'License','com_pixext.license','{"special":{"dbtable":"#__pixext_licenses","key":"id","type":"License","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/license.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_extension_id","targetTable":"#__pixext_extensions","targetColumn":"pixext_extension_id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.license')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'License', 
	`table` = '{"special":{"dbtable":"#__pixext_licenses","key":"id","type":"License","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/license.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_extension_id","targetTable":"#__pixext_extensions","targetColumn":"pixext_extension_id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.license');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Package','com_pixext.package','{"special":{"dbtable":"#__pixext_packages","key":"id","type":"Package","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/package.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.package')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Package', 
	`table` = '{"special":{"dbtable":"#__pixext_packages","key":"id","type":"Package","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/package.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.package');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Package Version','com_pixext.packageversion','{"special":{"dbtable":"#__pixext_package_versions","key":"id","type":"Packageversion","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/packageversion.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_package_id","targetTable":"#__pixext_packages","targetColumn":"pixext_package_id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.packageversion')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Package Version', 
	`table` = '{"special":{"dbtable":"#__pixext_package_versions","key":"id","type":"Package Version","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/packageversion.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_package_id","targetTable":"#__pixext_packages","targetColumn":"pixext_package_id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.packageversion');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Package License','com_pixext.packagelicense','{"special":{"dbtable":"#__pixext_package_licenses","key":"id","type":"Packagelicense","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/packagelicense.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_package_id","targetTable":"#__pixext_packages","targetColumn":"pixext_package_id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.packagelicense')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Package License', 
	`table` = '{"special":{"dbtable":"#__pixext_package_licenses","key":"id","type":"Package License","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/packagelicense.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_package_id","targetTable":"#__pixext_packages","targetColumn":"pixext_package_id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_pixext.packagelicense');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Package Extension Version','com_pixext.packageextensionversion','{"special":{"dbtable":"#__pixext_package_extension_versions","key":"id","type":"Packageextensionversion","prefix":"PixextTable"}}', '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/packageextensionversion.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_extension_version_id","targetTable":"#__pixext_versions","targetColumn":"pixext_version_id","displayColumn":"pixext_version_id"},{"sourceColumn":"pixext_package_version_id","targetTable":"#__pixext_package_versions","targetColumn":"pixext_package_version_id","displayColumn":"pixext_package_version_id"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_pixext.packageextensionversion')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Package Extension Version', 
	`table` = '{"special":{"dbtable":"#__pixext_package_extension_versions","key":"id","type":"Package Extension Version","prefix":"PixextTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_pixext\/models\/forms\/packageextensionversion.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"pixext_extension_version_id","targetTable":"#__pixext_versions","targetColumn":"pixext_version_id","displayColumn":"pixext_version_id"},{"sourceColumn":"pixext_package_version_id","targetTable":"#__pixext_package_versions","targetColumn":"pixext_package_version_id","displayColumn":"pixext_package_version_id"}]}'
WHERE (`type_alias` = 'com_pixext.packageextensionversion');
